# Generated by Django 2.2 on 2020-08-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200821_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, null=True)),
                ('receiver', models.CharField(max_length=255, null=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
